spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testCRUD
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Avenged7x123
  jpa:
   database: mysql
   show_sql: true
   hibernate:
    ddl-auto: create


---
environment : test
spring:
  datasource:
    url: jdbc:h2:mem:testCRUD
    driverClassName: org.h2.Driver
    username: root
    password: Avenged7x123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true


